[project]
name = "jupyter-run"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Brian E. Granger", email = "ellisonbg@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter-core>=5.7.2",
]

[project.scripts]
jupyter-run = "jupyter_run.commands.run:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
